### ISSUE TITLE
Denedim çalışmıyor Web.Core Hatalar veriyor

### ISSUE THREAD

**Issue by uzeyir06** [mehmetakbudak/CMS#1]
Denedim çalışmıyor Web.Core Hatalar veriyor

**Comment by mehmetakbudak** [comment]
startup projesi olarak CMS.Api projesi seçilmeli ve CMS.UI ayrıca çalıştırılmalıdır.

**Comment by uzeyir06** [comment]
Teşekkürler açtım güzel bi çalışma başlangıcı olmuş tebrikler
![Ekran Alıntısı](https://user-images.githubusercontent.com/56324298/150550818-a47cdd0c-04f0-461e-9aa8-133546237ed2.PNG)

**Comment by mehmetakbudak** [comment]
Üzerinde çalışmaya devam ediyorum. teşekkür ederim.
